### ISSUE TITLE
[BUG] Error: This app cannot be enabled because it makes the server unstable

### ISSUE THREAD

**Issue by MadWentzThere** [linuxserver/docker-nextcloud#425]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Cannot enable Talk app on Nextcloud

### Expected Behavior

Talk should enable

### Steps To Reproduce

Click on Apps
Scroll/Find "Talk"
Click *Download and Enable*

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
Unraid App Page
```

### Container logs

```bash
{"reqId":"HsIXGNlVuoIVP5Sr9mNy","level":3,"time":"2024-04-08T18:49:51+00:00","remoteAddr":"172.18.0.1","user":"--","app":"no app in context","method":"GET","url":"/ocs/v2.php/cloud/user","message":"Could not decrypt or decode encrypted session data","userAgent":"Mozilla/5.0 (iOS) Nextcloud-iOS/5.2.5","version":"28.0.4.1","exception":{"Exception":"Exception","Message":"HMAC does not match.","Code":0,"Trace":[{"file":"/app/www/public/lib/private/Security/Crypto.php","line":119,"function":"decryptWithoutSecret","class":"OC\\Security\\Crypto","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/app/www/public/lib/private/Session/CryptoSessionData.php","line":90,"function":"decrypt","class":"OC\\Security\\Crypto","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/app/www/public/lib/private/Session/CryptoSessionData.php","line":67,"function":"initializeSession","class":"OC\\Session\\CryptoSessionData","type":"->"},{"file":"/app/www/public/lib/private/Session/CryptoWrapper.php","line":112,"function":"__construct","class":"OC\\Session\\CryptoSessionData","type":"->"},{"file":"/app/www/public/lib/base.php","line":449,"function":"wrapSession","class":"OC\\Session\\CryptoWrapper","type":"->"},{"file":"/app/www/public/lib/base.php","line":705,"function":"initSession","class":"OC","type":"::"},{"file":"/app/www/public/lib/base.php","line":1200,"function":"init","class":"OC","type":"::"},{"file":"/app/www/public/ocs/v1.php","line":31,"args":["/app/www/public/lib/base.php"],"function":"require_once"},{"file":"/app/www/public/ocs/v2.php","line":23,"args":["/app/www/public/ocs/v1.php"],"function":"require_once"}],"File":"/app/www/public/lib/private/Security/Crypto.php","Line":158,"message":"Could not decrypt or decode encrypted session data","exception":[],"CustomMessage":"Could not decrypt or decode encrypted session data"},"id":"66144260bf2e5"}
```

**Comment by aptalca** [comment]
It's an upstream issue tracked there

**Comment by alexbelgium** [comment]
Hi, relevant PR upstream that should fix it : https://github.com/nextcloud/server/pull/44939

**Comment by alexbelgium** [comment]
Actually according to https://github.com/nextcloud/server/issues/44685 the solution is on the configuration of nginx, so the correction should be made here (haven't found out yet how)

**Comment by alexbelgium** [comment]
Actually, solution is simply to disable `fastcgi_param front_controller_active true` in https://github.com/linuxserver/docker-nextcloud/blob/f72ad27864a459ec5fcb0f86e49263e04b6a1e21/root/defaults/nginx/site-confs/default.conf.sample#L127

**Comment by dansity** [comment]
> Actually, solution is simply to disable `fastcgi_param front_controller_active true` in
> 
Do I need to do anything other than commenting this out? I have done it and restarted the docker. Still the same for me but now it is asking for the password before giving the same error.

**Comment by 279308** [comment]
> > Actually, solution is simply to disable `fastcgi_param front_controller_active true` in
> 
> Do I need to do anything other than commenting this out? I have done it and restarted the docker. Still the same for me but now it is asking for the password before giving the same error.

you need to change it in 

fastcgi_param front_controller_active ~~true~~ false

**Comment by dansity** [comment]
thank you, it should have been obvious. However the issue is still present to me even after setting it to false and restarting the docker.

**Comment by yzx1208** [comment]
> thank you, it should have been obvious. However the issue is still present to me even after setting it to false and restarting the docker.
> 
> edit: what worked for me is I went to the mysql database in adminer and changed the value in the oc_appconfig table from `no` to `yes` for the app I wanted.

how to ?

**Comment by Raphty** [comment]
@yzx1208 adminer is a tool with which you can fairly easily navigate through databases
https://hub.docker.com/_/adminer/

you connect to the database where you have you nextcloud tables and then open up the table list look for oc_appconfig and then navigate through the entries.

be careful! if you don't know what you are doing better don't!

**Comment by JYNXWARE** [comment]
> Actually, solution is simply to disable `fastcgi_param front_controller_active true` in
> 
> https://github.com/linuxserver/docker-nextcloud/blob/f72ad27864a459ec5fcb0f86e49263e04b6a1e21/root/defaults/nginx/site-confs/default.conf.sample#L127

I found this worked for me. Just edit default.conf, not the .sample file

**Comment by kesselb** [comment]
Some of those "This app cannot be enabled..." cases should be fixed by https://github.com/nextcloud/server/pull/45765 which was released with 29.0.3.

**Comment by ZombieLurker** [comment]
Same error happens on fresh install of latest linuxserver nextcloud 30 docker compose container. Unable to enable any app through the web browser. Was able to enable it with the occ command.

**Comment by alekvit** [comment]
> Same error happens on fresh install of latest linuxserver nextcloud 30 docker compose container. Unable to enable any app through the web browser. Was able to enable it with the occ command.

This is right! Only occ... Apps has installed and work, but still marked in GUI as not installed.
For reference (in docker's container) some commands:
sudo occ list;
sudo occ app:enable files_external;
sudo occ app:install mail
